This script will show the probability density function of rolling a d20 with or without advantage.

In [10]:
import numpy as np
D20_noAdvantage = np.random.rand(2,3)

In [11]:
D20_noAdvantage

array([[0.74682972, 0.3282613 , 0.30585209],
       [0.63658542, 0.81523165, 0.23258784]])

In [23]:
import random
D20_noAdvantage = random.choices(range(20), k=int(1e6))

In [21]:
N

1000000.0

In [84]:
D20_Advantage = np.array([random.choices(range(20), k=int(1e6)), random.choices(range(20), k=int(1e6))])

In [85]:
print(D20_Advantage.shape)

(2, 1000000)


In [87]:
test = np.max(D20_Advantage,axis=0)
print(test)
test.shape

[ 5 11 13 ...  2 11  9]


(1000000,)

In [94]:
print(D20_Advantage[:2])

[[ 1 11  6 ...  2  1  9]
 [ 5  5 13 ...  1 11  3]]


In [42]:
D20_AdvantageMax = max(D20_Advantage)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [98]:
testmat = [[2,4,6],[5,1,3],[7,8,9]]

In [99]:
testmat[:2]

[[2, 4, 6], [5, 1, 3]]

In [113]:
testmat[:2,:2]

TypeError: list indices must be integers or slices, not tuple