This script will show the probability density function of rolling a d20 with or without advantage.

In [10]:
import numpy as np
D20_noAdvantage = np.random.rand(2,3)

In [11]:
D20_noAdvantage

array([[0.74682972, 0.3282613 , 0.30585209],
       [0.63658542, 0.81523165, 0.23258784]])

In [23]:
import random
D20_noAdvantage = random.choices(range(20), k=int(1e6))

In [21]:
N

1000000.0

In [129]:
D20_Advantage = np.array([random.choices(range(20), k=int(1e6)), random.choices(range(20), k=int(1e6))])

In [130]:
print(D20_Advantage.shape)

(2, 1000000)


The output is (1e6,). The trailing comma indicates that this is a 1-tuple output, as opposed to the number 1e6.

In [136]:
D20_withAdvantage = np.max(D20_Advantage,axis=0)
print(test)
test.shape

[13 16 14 ... 16 12  5]


(1000000,)

The mean values of D20 and D20 with advantage are shown

In [138]:
print(np.average(D20_noAdvantage))
print(np.average(D20_withAdvantage))

9.50401
12.827322


In [ ]:
x = rgamma(1000, 3, .1)
hist(x, prob=T, br=30, col="skyblue2", main="n = 1000: GAMMA(3, .1)")
curve(dgamma(x, 3, .1), add=T, lwd=2, col="orange")
abline(v = 55.81, lwd=2, col="blue")
abline(v = 53.2232, lwd=2, col="brown", lty="dotted")

In [139]:
from scipy.stats import dgamma
r = dgamma.rvs(1.1, size=1000)
ax.hist(r, density=True, histtype='stepfilled', alpha=0.2)
ax.legend(loc='best', frameon=False)
plt.show()

NameError: name 'ax' is not defined

Must define matrix as np.array() to allow below indexing 'testmat[0:2,0:2]'

In [132]:
testmat = np.array([[2,4,6],[5,1,3],[7,8,9]])

In [133]:
print(testmat[0:2,0:2])

[[2 4]
 [5 1]]


In [119]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) 

[[2 3 4]
 [7 8 9]]


In [134]:
np.average(testmat)

np.float64(5.0)

In [135]:
np.average(testmat,axis=1)

array([4., 3., 8.])