In [1]:
[[1., 0., 0.],
 [0., 1., 2.]]

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:

print(a.shape)

print(a.ndim)

print(a.dtype.name)

(3, 5)
2
int64


In [8]:
print(a.itemsize)

print(a.size)

print(type(a))

b = np.array([6, 7, 8])

print(type(b))

8
15
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
c = range(10,30,5)

In [14]:
d=np.arange(10,30,5)

In [15]:
print(type(c))
print(type(d))

<class 'range'>
<class 'numpy.ndarray'>


In [16]:
#np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported, this command prints entire array


In [19]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=np.int_) #sets dtype as integer instead of float
b = rg.random((2, 3))
a *= 3 #sets a = a*3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [20]:
b += a #sets b = b+a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [28]:
a*b

array([[10.53546487, 11.85139109,  9.43247884],
       [11.84594834,  9.93549436, 10.26997935]])

In [37]:
c = np.ones((2,3),dtype=np.int_)
type(c)
c

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
c*=b #this does not work because c and b are different type, int vs float.
c

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [39]:
c = np.ones((2,3))
type(c)
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
c*=b
c

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])